version: '3'
services:
  fastapi:
    container_name: fapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/workspace
    ports:
      - "9000:9000" 
    working_dir: /workspace
    tty: true
